---
  - name: Install needed software
    apt: name={{ item }} state=present update_cache=yes cache_valid_time=1800
    with_items:
      - keepalived
      - iptables-persistent

  - name: Configure keepalived
    template: src=keepalived.conf.j2 dest=/etc/keepalived/keepalived.conf owner=root group=root mode=0644
    notify: restart keepalived

  - name: Configure sysctl dropin
    template: src=sysctl.conf.j2 dest=/etc/sysctl.d/ansible.conf owner=root group=root mode=0755
    notify: reload sysctl

  - name: Configure iptables
    template: src=iptables.rules.j2 dest=/etc/iptables/rules.v4 owner=root group=root mode=0644
    notify: reload iptables

  - name: Enable services
    service: name={{ item }} enabled=yes state=started
    with_items:
      - sshd
      - keepalived
      - netfilter-persistent
