---
  - name: Install needed software
    become: True
    apt:
      name:
        - keepalived
        - iptables-persistent
      state: present
      cache_valid_time: 1800

  - name: Configure keepalived
    become: True
    template:
      src: keepalived.conf.j2
      dest: /etc/keepalived/keepalived.conf
      owner: root
      group: root
      mode: 0644
    notify: restart keepalived
    when: router_ha_ips != []

  - name: Configure sysctl dropin
    become: True
    sysctl:
      name: "{{ item.name }}"
      value: "{{ item.value }}"
      sysctl_file: /etc/sysctl.d/ansible_router.conf
      reload: True
      state: present
    with_items:
      - { name: 'net.ipv4.ip_forward', value: '1' }
      - { name: 'net.ipv4.ip_nonlocal_bind', value: '1' }
      - { name: 'net.ipv6.ip_nonlocal_bind', value: '1' }

  - name: Configure iptables
    become: True
    template:
      src: iptables.rules.j2
      dest: /etc/iptables/rules.v4
      owner: root
      group: root
      mode: 0644
    notify: reload iptables

  - name: Enable services
    become: True
    service:
      name: "{{ item }}"
      enabled: True
      state: started
    with_items:
      - netfilter-persistent

  - name: Enable services
    become: True
    service:
      name: "{{ item }}"
      enabled: True
      state: started
    with_items:
      - keepalived
    when: router_ha_ips != []
