---
  - name: restart keepalived
    service: name=keepalived state=restarted

  - name: reload sysctl
    service: name=systemd-sysctl state=restarted

  - name: reload systemd
    systemd: daemon_reload=yes

  - name: reload iptables
    service: name=netfilter-persistent state=restarted
